### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by bgp799** [anwarMZ/CoMW#1]
Hi Zohaib!

I was hoping you could help me with a problem om pallas server regarding installation of CoMW.

When the CoMW.yml file runs I get the following error message: seen in the picture.

Can you help me understand what I need to do to fix this?

I only have terminal access to pallas.

Kind regards,
Jon
![Screenshot from 2020-04-17 19-56-36](https://user-images.githubusercontent.com/63874174/79601709-8aa49a80-80e9-11ea-8922-83d9085f55af.png)

**Comment by anwarMZ** [comment]
Hi Jon, 
It seems like `cmake 3.3.1-0` was deprecated in `Anaconda` channel from where I was trying to access it. Now that `sword` has updated version in `conda` we don't need that at all. I have changed  two files 

- [CoMW.yml](https://github.com/anwarMZ/CoMW/blob/master/CoMW.yml)

- [install.sh](https://github.com/anwarMZ/CoMW/blob/master/install.sh)

Either download these two files and replace in your `CoMW` directory or just re-download the `CoMW` repository and try the installation instructions again. 

Best, 
Zohaib

**Comment by bgp799** [comment]
Hi!
Installation seems to be working now ;-). Thx!
Here is a screen dump of the last part!

![Screenshot from 2020-04-18 08-29-19](https://user-images.githubusercontent.com/63874174/79630083-cde52480-814e-11ea-92b2-3d54807d7cb8.png)
