### ISSUE TITLE
When running script align_contigs_to_database.py no tsv-files are created 

### ISSUE THREAD

**Issue by bgp799** [anwarMZ/CoMW#2]
Hi Zohaib!
I have been running all scripts including filter_table_by_abundance.py successfully. When running the script align_contigs_to_database.py I get the following output from the script:
![Screenshot from 2020-05-03 16-50-46](https://user-images.githubusercontent.com/63874174/80917386-d3518a00-8d5e-11ea-82fd-15fa0a1eaf52.png)
It seemingly can't find the tsv-files for concatenation into one file containing all results, but looking at the output it looks like these cat command errors are found in the middle of the script??? and not in the end as expected from the script.
When I investigate deeper I find that when trying to run a command like:
sword -i ./Step5_align_contigs_to_database/TempFiles/Translated_step4_AbundanceFiltered_Trinity.09.fasta -t 12 -o ./Step5_align_contigs_to_database/TempFiles/Translated_step4_AbundanceFiltered_Trinity.09.result.tsv -f bm9 -j /mibi/Jon/CoMW/databases/NCyc_100.faa -c 30000
I get "Illegal instruction" as output. I got the syntax above from the script and even if I shave arguments down to just -i -o -j it gives the same error message. I have checked the -i file and they seem to be in the correct fasta-format. I have also checked lengths of sequences. The longest is just above 2200 bytes, so no problem there (checked because Sword-author on Github recorded an issue with lengths of sequences above 65k).
Can you help with this? Do you have any ideas. I also tried with original Trinity.fasta file.
Kr,
Jon

**Comment by anwarMZ** [comment]
Hi Jon, 
Thanks for bringing this up. Actually another colleague had same error. It works well on my system. I can check and discuss with `sword` author and see if he has had same error from someone else. Also could you suggest the system specifications that you are using. 
Zohaib

**Comment by anwarMZ** [comment]
This issue is specific to `conda` package `sword` and how it supports different servers. `sword` author is working on `AVX2` instructions and adjusting flag `-mno-avx2` in this [issue](https://github.com/rvaser/sword/issues/4).

There will updates on this later ...

**Comment by anwarMZ** [comment]
@bgp799 If you now download `CoMW.yml` and do the following.

`conda remove --name CoMW --all`
`conda clean -a`
`conda env create -f ./CoMW.yml` #With Updated `CoMW.yml` file

and try to rerun the command.

Zohaib

**Comment by bgp799** [comment]
Hi Zohaib!
The script is running. Thank you very much for responding quickly and supporting communications! 
Kind regards,
Jon
