### ISSUE TITLE
Error message i script Mapping Orthologs to count table

### ISSUE THREAD

**Issue by bgp799** [anwarMZ/CoMW#4]
Hi, I get the following error message from running Mapping orthologs to count table:
Error in library(plyr) : there is no package called ‘plyr’
Execution halted
CoMW environment is activated. The R-script is trying to retrieve library plyr.
Can you help with this?
Kr,
Jon

**Comment by anwarMZ** [comment]
Hi Jon, I can see this is a very small issue with `conda` not implicitly installing this package. I will update the `CoMW.yml` file soon and let you know the steps to follow. 
Thanks, 
Zohaib

**Comment by anwarMZ** [comment]
@bgp799 I have now fixed the package error. Could you please do the following and update. 

`conda remove --name CoMW --all`
`conda clean -a`
`conda env create -f ./CoMW.yml #With Updated CoMW.yml file`

I have also updated the script file `annotate_count_table.py`, so I suggest downloading the new [script](https://github.com/anwarMZ/CoMW/blob/master/scripts/annotate_count_table.py) and replacing the older one in `./scripts` folder. 

This should work well.
